# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    env:
      XCODE_VERSION: 'Xcode_16.3'

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/$XCODE_VERSION.app"
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Lint
      run: swiftlint lint --strict --quiet
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test
